### ISSUE TITLE
relative path exporting the image failed

### ISSUE THREAD

**Issue by jianxiashao** [tdaykin/obsidian_image_collector#1]
I added the image using a relative path, so exporting the image failed.
![2024-02-27_004620](https://github.com/tdaykin/obsidian_image_collector/assets/11446214/6e655c25-cedd-4b64-93ec-2f3117646b56)
![2024-02-27_005025](https://github.com/tdaykin/obsidian_image_collector/assets/11446214/9b3bbcd5-cbba-4f9c-a587-7eeed856dfcd)

**Comment by tdaykin** [comment]
Thanks for letting me know, I will try and have the issue solved over the weekend! 

If you are wondering, my links are structured like this: 

![[IMG_3B211AF67617-1.jpeg]]

I have a folder called attachments in obsidian where I store all images. In settings > files and links > default location for new attachments and set your location. then from there you can place images, I have found that helped me organize a lot.

**Comment by jianxiashao** [comment]
Your link is in wiki format, mine is in markdown format, because the general markdown editor can't recognize it, so I turned off the wiki link

**Comment by tdaykin** [comment]
Try updating the plugin from Obsidian, or download the new release from GitHub. I think it is fixed now, please let me know if it works for you.

**Comment by jianxiashao** [comment]
This md file has 4 pictures，but something went wrong
![2024-03-03_000349](https://github.com/tdaykin/obsidian_image_collector/assets/11446214/7b60c83c-0f96-4b47-a56d-08bdf4e6f8ab)
![2024-03-03_000546](https://github.com/tdaykin/obsidian_image_collector/assets/11446214/d76eb235-8ec4-48fa-8aa9-e4d387641b12)
![2024-03-03_000934](https://github.com/tdaykin/obsidian_image_collector/assets/11446214/14d94e4a-9f3f-4450-8297-519cff5a8c90)
![2024-03-03_001103](https://github.com/tdaykin/obsidian_image_collector/assets/11446214/0314405e-d460-40af-babb-9d8c96b353b1)

**Comment by tdaykin** [comment]
Hmm, okay, so I do run into that error when I have run the command twice, as the pictures are already in the desired folder. I will continue looking for a fix over the weekend. Sorry it is still not working 😢, thank you for figuring it out with me.

**Comment by jianxiashao** [comment]
👌

**Comment by tdaykin** [comment]
Please try to update to version 1.0.2 and see if you are still having an issue, if so, please let me know. 

I tried this with markdown links and it seems to work for me.

**Comment by jianxiashao** [comment]
Everything works fine now, thank you very much

**Comment by tdaykin** [comment]
You are welcome and thank you for finding the bug! Hope the plugin is useful.
