### ISSUE TITLE
Resolved. Thank you very much.

### ISSUE THREAD

**Issue by zhouxinghong** [tdaykin/obsidian_image_collector#3]
Friends! Hello! Thank you very much for this cool plugin 👍😜 May I ask where the collected images are stored?

I am really unable to find it!

**Comment by tdaykin** [comment]
In your note, open the command palette and type/select "image collector", or right click on your note and select towards the bottom of the menu to "export images". The images will then appear in a folder named as your note (note_name images) stored on the left where your other folders are.

**Comment by zhouxinghong** [comment]
I found the reason is that the export fails.
The message says: image could not be found.
Image format is:
`![](https://cd.u-ti.com/image/10/content/70033/n6FoytytgfgfgtyfdfrtrtrtIt.jpg)`

**Comment by zhouxinghong** [comment]
Improvement Suggestion:
1.It's best to keep the exported image folder in the same directory as the .md file, for example:
d:\xxxxx\ddddd images
d:\xxxxx\ddddd.md

2.Support customized file directory name format, e.g.:
d:\xxxxx\ddddd-images
or
d:\xxxxx\ddddd_images
or
d:\xxxxx\images_ddddd
or
d:\xxxxx\images-dddddd
...

**Comment by zhouxinghong** [comment]
Resolved. Thank you very much.
